import bcrypt from 'bcrypt-nodejs';

const user = [
  {
    id: 1,
    firstName: 'ruhimbaza',
    lastName: 'Bertin',
    email: 'ruhimbazab@gmail.com',
    password: bcrypt.hashSync('bertin123'),
    address: 'kigali',
    bio: 'scientist',
    occupation: 'software development',
    expertise: 'sostware architecture',
    userType: 'user',
  },
  {
    id: 2,
    firstName: 'ahishakiye',
    lastName: 'aline',
    email: 'aline@gmail.com',
    password: bcrypt.hashSync('aline123'),
    address: 'Nairobi',
    bio: 'researcher',
    occupation: 'advocacy',
    expertise: 'teaching',
    userType: 'mentor',
  },
  {
    id: 3,
    firstName: 'ngarambe',
    lastName: 'antoine',
    email: 'antoine@gmail.com',
    password: bcrypt.hashSync('antoine123'),
    address: 'legos',
    bio: 'something',
    occupation: 'maintenance',
    expertise: 'maintainning systems',
    userType: 'admin',
  },
  {
    id: 4,
    firstName: 'ngarambe',
    lastName: 'antoinette',
    email: 'antoinette@gmail.com',
    password: bcrypt.hashSync('antoine123'),
    address: 'legos',
    bio: 'something',
    occupation: 'maintenance',
    expertise: 'maintainning systems',
    userType: 'mentor',
  },
  {
    id: 5,
    firstName: 'ngarambe',
    lastName: 'Niyitegeka',
    email: 'alphonsine@gmail.com',
    password: bcrypt.hashSync('alphonsine123'),
    address: 'legos',
    bio: 'something',
    occupation: 'maintenance',
    expertise: 'maintainning systems',
    userType: 'user',
  },
];

export default user;
